fuego/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url( r'^natality/', include( 'natality.urls', namespace="natality" ) ),
	url( r'^$', include( 'vizapp.urls', namespace="vizapp" ) ),
	url( r'^admin/', include( admin.site.urls ) ),
]

natality/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url( r'^$', views.IndexView.as_view(), name='index' ),
	url( r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail' ),
	url( r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results' ),
	url( r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote' ),
]

vizapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url( r'^$', views.IndexView.as_view(), name='index' ),
]

natality/models.py
from django.db import models
import datetime
from django.utils import timezone


# TEST CODE

class Question( models.Model ):
	question_text = models.CharField( max_length = 200 )
	pub_date      = models.DateTimeField( 'date published' )
	def was_published_recently( self ):
		return self.pub_date >= timezone.now() - datetime.timedelta( days = 1 )
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	def __unicode__( self ):
		return self.question_text

class Choice( models.Model ):
	question    = models.ForeignKey( Question )
	choice_text = models.CharField( max_length = 200 )
	votes       = models.IntegerField( default = 0 )
	def __unicode__( self ):
		return self.choice_text

# END TEST CODE

vizapp/models.py
from django.db import models

# Create your models here.

natality/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader
from django.views import generic
from .models import Question, Choice

"""
def index( request ):
	latest_question_list = Question.objects.order_by( '-pub_date' )[:5]
	context = { 'latest_question_list' : latest_question_list }
	return render( request, 'natality/index.html', context )

def detail( request, question_id ):
	question = get_object_or_404( Question, pk=question_id )
	return render( request, 'natality/detail.html', {'question':question} )

def results( request, question_id ):
	question = get_object_or_404( Question, pk=question_id )
	return render( request, 'natality/results.html', {'question':question } )
"""

class IndexView( generic.ListView ):
	template_name = 'natality/index.html'
	context_object_name = 'latest_question_list'
	def get_queryset( self ):
		return Question.objects.order_by( '-pub_date' )[:5]

class DetailView( generic.DetailView ):
	model = Question
	template_name = 'natality/detail.html'

class ResultsView( generic.DetailView ):
	model = Question
	template_name = 'natality/results.html'

def vote( request, question_id ):
	p = get_object_or_404( Question, pk=question_id )
	try:
		selected_choice = p.choice_set.get( pk=request.POST['choice'] )
	except (KeyError, Choice.DoesNotExist ):
		return render( request, 'polls/detail.html', {
			'question': p,
			'error_message': "You didn't select a choice.",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect( reverse( 'natality:results', args=(p.id,) ) )

vizapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader
from django.views import generic
#from .models import Question, Choice


class IndexView( generic.TemplateView ):
	template_name = 'vizapp/index.html'

natality/templates/natality/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action ="{% url 'natality:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type='radio' name='choice' id='choice{{ forloop.counter }}' value='{{choice.id}}' />
		<label for='choice{{ forloop.counter }}'>{{choice.choice_text}}</label><br />
	{% endfor %}
	<input type='submit' value='Vote' />
</form>

natality/templates/natality/index.html
{% load staticfiles %}
<link rel='stylesheet' type='text/css' href="{% static 'natality/style.css' %}" />

{% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
			<li>
				<a href="{% url 'natality:detail' question.id %}">{{ question.question_text }}</a>
			</li>
		{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

natality/templates/natality/results.html
<h1>{{ question.question_text }}</h1>

<ul>
	{% for choice in question.choice_set.all %}
		<li>
			{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}
		</li>
	{% endfor %}
</ul>
<a href="{% url 'natality:detail' question.id %}">Vote again?</a>

vizapp/templates/vizapp/about.html
{% extends 'vizapp/base.html' %}
{% block content %}
{% load staticfiles %}
<img src="{% static 'vizapp/jn_nod.gif' %}" alt="MMMMMMM" style="width:700px; height:500px; margin-left:25%; margin-top:5em;">

<script>
$(document).ready( function(){
	$("#nav_about").addClass( "nav_selected" );
	$("#nav_home").click( function() { window.location.href = "/"; });
	$("#nav_datasets").click( function() { window.location.href = "/datasets/"; });
});
</script>

{% endblock content %}

vizapp/templates/vizapp/base.html
<!DOCTYPE html>
<html lang='en'>
	<head>
		<meta charset='UTF-8'>
		<title>Los Fuegos Papiis</title>
		{% load staticfiles %}
		<!-- JS Imports  -->
		<script type='text/javascript' src="{% static 'vizapp/jquery-1.11.3.min.js' %}"></script>
		<script src="//d3js.org/d3.v3.min.js"></script>
		<script src="//d3js.org/topojson.v1.min.js"></script>
		<!-- CSS Imports -->
		<link rel='stylesheet' type='text/css'     href="{% static 'vizapp/base.css' %}" />
		<link rel='shortcut icon' type='image/png' href="{% static 'vizapp/fuego.ico' %}" />
		<!-- Font Imports -->
		<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<div id='site_container'>
			<div id='header_container'>
				<div id='title_container'>
					<div id='main_title'>
						Los Fuegos Papiss
					</div>
					<div id='main_subtitle'>
						OR WHATEVER THE FUCK OUR LAST NAME IS
					</div>
				</div> <!-- title_container -->
				<div id='nav_container'>
					<div id='nav_home' class='nav_item'>Home</div>
					<div id='nav_datasets' class='nav_item'>Datasets</div>
					<div id='nav_about' class='nav_item'>About</div>
					<div class='clear'></div>
				</div> <!-- nav_container -->
				<div class='clear'></div>
			</div>	<!-- header_container -->
			{% block content %}{% endblock content %}
		</div> <!-- site_container -->
			<div id='footer_container'>
				<div id='footer_text'>
					FSU-CEN4020 - Hernandez, Nabors, Reynes
				</div>
				<div class='clear'></div>
			</div> <!-- footer_container -->
	</body>
</html>

vizapp/templates/vizapp/datasets.html
{% extends 'vizapp/base.html' %}
{% block content %}

<div id='datasets_container'>
	{% if cat_list %}
		{% for cat in cat_list %}
			<div class='cat_container'>
				<div class='cat_title'>{{ cat.name }}</div>
				<hr style='width:90%;' />
				<div class='cat_content'>
					{% for vis in vis_list %}
						{% if vis.category == cat %}
							<div id='{{vis.template_slug}}_container' class='index_latest_container cat_vis_box'>
								<div class='index_latest_name'>{{vis.vis_name}}</div>
								<hr style='width: 80%;' />
								<div class='index_latest_descrip_title'>Short Description:</div>
								<div class='index_latest_descrip'>{{vis.short_description}}</div>
								<div class='index_date_container'>
									<div class='index_latest_descrip_title'>Date Published:</div>
									<div class='index_date_pub'>{{vis.pub_date}}</div>
									<div class='index_latest_descrip_title'>Last Edited:</div>
									<div class='index_date_edit'>{{vis.last_edit}}</div>
								</div>
							</div>
							<script>
								$("#{{vis.template_slug}}_container").click( function(){ window.location.href = '/datasets/{{vis.template_slug}}'; });
							</script>
						{% endif %}
					{% endfor %}
					<div class='clear'></div>
				</div>
			</div>
		{% endfor %}

	{% else %}
		No data to display.
	{% endif %}

</div>


<script>
$(document).ready( function(){
	$("#nav_datasets").addClass( "nav_selected" );
	$("#nav_home").click( function() { window.location.href = "/"; });
	$("#nav_about").click( function() { window.location.href = "/about/"; });
});
</script>

{% endblock content %}

vizapp/templates/vizapp/index.html
{% extends 'vizapp/base.html' %}
{% block content %}
	<!--INDEX PLACEHOLDER-->
{% endblock content %}

vizapp/templates/vizapp/usa_natality_2012.html
{% extends 'vizapp/base.html' %}
{% block content %}

<script>
$(document).ready( function(){
	$("#nav_home").click( function() { window.location.href = "/"; });
	$("#nav_datasets").click( function() { window.location.href = "/datasets/"; });
	$("#nav_about").click( function() { window.location.href = "/about/"; });
});
</script>

{% endblock content %}